#ifndef GAMEWORLD_H
#define GAMEWORLD_H

#include "core/Utils.h"
#include "ai/Controller.h"
#include "core/GameCommand.h"
#include "core/GameSnapshot.h"
#include "simulation/MapGenerator.h"
#include "economy/Player.h"
#include "ui/Renderer.h"

class AudioSystem;
class PathingService;

#include <cstdint>
#include <deque>
#include <vector>

class PlayerHandler
{
    public:
        PlayerHandler() = default;

        // Owns all players participating in the current world.
        std::map<int, std::unique_ptr<Player>> players;
};

// Owns the playable simulation state, including map, players and persistence.
class GameWorld
{
    public:
        GameWorld() = default;

        // Creates a new world with generated terrain and starting entities.
        void InitWorld(std::string, Renderer*, AudioSystem* audio = nullptr, MapParameters params = {});
        // Creates a deterministic multiplayer world with server-assigned player slots.
        void InitMultiplayerWorld(std::string name, Renderer* renderer, AudioSystem* audio, MapParameters params, int localPlayerId, bool authoritativeHost);
        // Writes the current world state to a save file.
        bool SaveToFile(const std::string& path) const;
        // Rebuilds the world state from a save file.
        bool LoadFromFile(const std::string& path, Renderer* renderer, AudioSystem* audio = nullptr);
        // Queues an intent generated by a human, AI or remote player.
        std::uint64_t SubmitCommand(const GameCommand& command);
        // Queues an intent and assigns an authoritative target tick when needed.
        std::uint64_t SubmitCommand(const GameCommand& command, std::uint64_t minimumTargetTick);
        // Returns command accept/reject results emitted since the last consume.
        std::vector<GameCommandResult> ConsumeCommandResults();
        // Applies a command received from an authoritative host to a client-side mirror.
        bool ApplyAuthoritativeCommand(const GameCommand& command);
        // Advances the simulation by elapsed time in seconds.
        void Update(double);
        // Advances only authoritative gameplay state, without touching visual layers.
        void UpdateSimulation(double dt);
        // BUG 3b/3d: pull supply for every deployed division from the nearest friendly
        // stockpile within SupplyRange tiles. Also called from UpdateSimulation (1 Hz).
        // Exposed so tests can drive it directly without a full world tick.
        void ResupplyDeployedDivisions();
        // Draws terrain, roads, buildings and territory overlays.
        void DrawMap();
        // Captures render-safe world state for another thread.
        GameSnapshot BuildSnapshot() const;
        // Computes a deterministic low-cost gameplay checksum for mirror validation.
        std::uint64_t BuildChecksum() const;
        // Returns the player controlled by local UI.
        int GetLocalPlayerId() const { return localPlayerId; }
        // True when a player's Headquarters has been captured (player eliminated).
        bool IsPlayerDefeated(int playerId) const;
        // Id of the sole surviving player once every other has been eliminated
        // (a decided game); -1 while two or more players remain. Deterministic.
        int GetVictorPlayerId() const;
        // Returns the authoritative simulation tick counter.
        std::uint64_t GetSimulationTick() const { return simulationTick; }
        // Returns the global pathfinding service (ETAP 3.4 integration point)
        PathingService* GetPathingService() const { return pathingService.get(); }

    private:
        // Creates one player and initializes display/controller metadata.
        Player* CreatePlayer(int id, PlayerControllerType controllerType, const std::string& name, Color color);
        // Creates HQ, starting territory, village and start road for one player.
        Vec2i CreateStartingBase(Player* player, Vec2i hqAnchor, unsigned int seed);
        // Attaches the right controller implementation for one player.
        void AttachControllerForPlayer(Player* player);
        // Advances all input/AI/network controllers.
        void UpdateControllers(double dt);
        // Executes every queued command in submission order.
        void ProcessCommands();
        // Validates and applies one command to the simulation.
        bool ExecuteCommand(const GameCommand& command);
    
    public:
        TileMap tilemap;
        PlayerHandler playerHandler;
        Renderer*     render{nullptr};
        AudioSystem*  audio{nullptr};
        std::string worldName{"default"};
        int localPlayerId{0};

    private:
        std::deque<GameCommand> pendingCommands;
        std::vector<GameCommandResult> commandResults;
        std::vector<std::unique_ptr<IController>> controllers;
        std::unique_ptr<PathingService> pathingService;
        std::uint64_t nextCommandId{1};
        std::uint64_t simulationTick{0};
        Vec2f cachedCameraTarget{std::numeric_limits<float>::max(), std::numeric_limits<float>::max()};
        float cachedCameraZoom{-1.0f};
};


#endif
