#ifndef GAMEWORLD_H
#define GAMEWORLD_H

#include "Utils.h"
#include "Controller.h"
#include "GameCommand.h"
#include "MapGenerator.h"
#include "Player.h"
#include "Renderer.h"

#include <cstdint>
#include <deque>
#include <vector>

class PlayerHandler
{
    public:
        PlayerHandler() = default;

        // Owns all players participating in the current world.
        std::map<int, std::unique_ptr<Player>> players;
};

// Owns the playable simulation state, including map, players and persistence.
class GameWorld
{
    public:
        GameWorld() = default;

        // Creates a new world with generated terrain and starting entities.
        void InitWorld(std::string, Renderer*, MapParameters params = {});
        // Creates a deterministic multiplayer world with server-assigned player slots.
        void InitMultiplayerWorld(std::string name, Renderer* renderer, MapParameters params, int localPlayerId, bool authoritativeHost);
        // Writes the current world state to a save file.
        bool SaveToFile(const std::string& path) const;
        // Rebuilds the world state from a save file.
        bool LoadFromFile(const std::string& path, Renderer* renderer);
        // Queues an intent generated by a human, AI or remote player.
        std::uint64_t SubmitCommand(const GameCommand& command);
        // Queues an intent and assigns an authoritative target tick when needed.
        std::uint64_t SubmitCommand(const GameCommand& command, std::uint64_t minimumTargetTick);
        // Returns command accept/reject results emitted since the last consume.
        std::vector<GameCommandResult> ConsumeCommandResults();
        // Applies a command received from an authoritative host to a client-side mirror.
        bool ApplyAuthoritativeCommand(const GameCommand& command);
        // Advances the simulation by elapsed time in seconds.
        void Update(double);
        // Advances only authoritative gameplay state, without touching visual layers.
        void UpdateSimulation(double dt);
        // Draws terrain, roads, buildings and territory overlays.
        void DrawMap();
        // Returns the player controlled by local UI.
        int GetLocalPlayerId() const { return localPlayerId; }
        // Returns the authoritative simulation tick counter.
        std::uint64_t GetSimulationTick() const { return simulationTick; }

    private:
        // Creates one player and initializes display/controller metadata.
        Player* CreatePlayer(int id, PlayerControllerType controllerType, const std::string& name, Color color);
        // Creates HQ, starting territory, village and start road for one player.
        Vec2i CreateStartingBase(Player* player, Vec2i hqAnchor, unsigned int seed);
        // Attaches the right controller implementation for one player.
        void AttachControllerForPlayer(Player* player);
        // Advances all input/AI/network controllers.
        void UpdateControllers(double dt);
        // Executes every queued command in submission order.
        void ProcessCommands();
        // Validates and applies one command to the simulation.
        bool ExecuteCommand(const GameCommand& command);
    
    public:
        TileMap tilemap;
        PlayerHandler playerHandler;
        Renderer* render{nullptr};
        std::string worldName{"default"};
        int localPlayerId{0};

    private:
        std::deque<GameCommand> pendingCommands;
        std::vector<GameCommandResult> commandResults;
        std::vector<std::unique_ptr<IController>> controllers;
        std::uint64_t nextCommandId{1};
        std::uint64_t simulationTick{0};
        Vec2f cachedCameraTarget{std::numeric_limits<float>::max(), std::numeric_limits<float>::max()};
        float cachedCameraZoom{-1.0f};
};


#endif
