#include "scenes/Scenes.h"

#include <array>
#include <cmath>
#include <mutex>

#include "warfare/UnitDefinition.h"

namespace
{
    struct TutorialPopupDefinition
    {
        TutorialTriggerType trigger;
        const char* title;
        const char* body;
        const char* action;
        TutorialTriggerType nextTrigger;
        bool dimBackground;
    };

    // Popup text is data, not a separate function per step. New milestones can
    // be added here and triggered by TutorialTriggerEvent from any system.
    constexpr std::array<TutorialPopupDefinition, 9> PopupDefinitions{{
        {
            TutorialTriggerType::None,
            "Welcome to the tutorial",
            "Your goal is to build a functioning state, secure its logistics and conquer every opponent. "
            "We will cover camera controls, production, roads, defence and attack step by step. "
            "Whenever an instruction window is open, the simulation is paused so you can read at your own pace.",
            "Continue",
            TutorialTriggerType::PracticeIntro,
            true
        },
        {
            TutorialTriggerType::PracticeIntro,
            "Practice: production and logistics",
            "Production buildings turn terrain resources into the materials your settlement needs. "
            "A Woodcutter harvests {resource}Wood{/resource} from a forest, but the resource must still reach storage or its next consumer. "
            "Roads are the physical logistics network: they carry shipments, have capacity and can become bottlenecks. "
            "Your next objective is to pan the camera with {icon:mouse_mmb}, press {icon:key_q} to open the build panel, "
            "choose Woodcutter and place it on a forest tile.",
            "Start practice",
            TutorialTriggerType::None,
            true
        },
        {
            TutorialTriggerType::BuildComplete,
            "Roads keep production alive",
            "The Woodcutter is complete. A valid route is a continuous four-directional chain of your Road tiles: "
            "the first tile must touch the Woodcutter footprint and the last tile must touch the Headquarters footprint. "
            "Diagonal-only gaps do not connect, and every tile in the chain must belong to you. "
            "Press {icon:key_r} to enter Road Build Mode, then place or drag roads with {icon:mouse_lmb} from the Woodcutter to the Headquarters. "
            "Objective: create a Woodcutter-Headquarters connection.",
            "Connect Woodcutter",
            TutorialTriggerType::None,
            true
        },
        {
            TutorialTriggerType::LogisticsConnected,
            "Manpower, food and productivity",
            "Villages generate manpower over time. Free manpower is the pool used by buildings and armies; "
            "production buildings assign workers from it, and their worker output depends on how many workers are available. "
            "People must be fed: food provisions are produced by the food chain and delivered through logistics. "
            "The food supply percentage affects Food productivity, so an empty food network slows every worker down. "
            "The Woodcutter panel is open behind this window; highlighted rows show workers, worker output and food productivity. "
            "The top HUD highlights manpower and food supply.",
            "Continue",
            TutorialTriggerType::BasicResourcesIntro,
            false
        },
        {
            TutorialTriggerType::BasicResourcesIntro,
            "Next objective: basic materials",
            "Wood is consumed by Lumber Mills and by construction, so one Woodcutter will soon be stretched thin. Build a second Woodcutter. "
            "Now establish the four basic material chains. Woodcutters harvest {resource}Wood{/resource} and Lumber Mills turn it into {resource}Planks{/resource}. "
            "A Mine on a {resource}Stone{/resource} deposit produces {resource}Stone{/resource}. The same Mine extracts {resource}Iron Ore{/resource} and {resource}Coal{/resource} from their deposits; "
            "{resource}Iron Ore{/resource} is smelted into {resource}Iron{/resource}, while {resource}Coal{/resource} also fuels the Foundry. "
            "Place producers on matching deposits, connect them to storage and consumers with roads, and keep the routes supplied. "
            "Objective: build a second Woodcutter and start production of {resource}Planks{/resource}, {resource}Stone{/resource}, {resource}Iron{/resource} and {resource}Coal{/resource}.",
            "Start production",
            TutorialTriggerType::None,
            true
        },
        {
            TutorialTriggerType::BasicProductionComplete,
            "Food keeps the state running",
            "Manpower and defensive towers both require food. People are generated by villages, but they stay productive only when food reaches them through the logistics network. "
            "Build the complete chain: a Well produces {resource}Water{/resource}; a Wheat Farm uses Water to produce {resource}Wheat{/resource}; "
            "a Windmill turns Wheat into {resource}Flour{/resource}; and a Bakery combines Flour and Water into {resource}Bread{/resource}. "
            "A Hunter's Hut supplies {resource}Meat{/resource}. The Inn consumes Bread, Meat and Water to produce {resource}Food Provisions{/resource}. "
            "Connect every step with roads, keep a reserve in storage, and make sure villages and defensive towers can receive Food Provisions. "
            "Objective: build the food chain, including a Hunter's Hut and an Inn, then feed your population and towers.",
            "Start food production",
            TutorialTriggerType::None,
            true
        },
        {
            TutorialTriggerType::FoodChainComplete,
            "Decisions shape your state",
            "Decisions are political choices made by the rulers of your settlement. They are free to start: the only cost is time. "
            "Each decision grants a lasting bonus, but only one can be active at a time, so choose the policy that best fits your plan. "
            "Open Decisions and select any available first decision. It will begin immediately and continue in the background while you play.",
            "Continue to Decisions",
            TutorialTriggerType::None,
            true
        },
        {
            TutorialTriggerType::DecisionSelected,
            "Defend the settlement",
            "Your first political decision is underway. Now prepare for an attack. An enemy force is marching along the military road toward your Headquarters. "
            "Build a Defense Tower near the route, connect it to your Headquarters with your normal road network, and keep the route supplied with {resource}Arrows{/resource}. "
            "The Headquarters already has a small reserve of arrows for this first defence. The local area and the attackers' route will be revealed while the attack is in progress. "
            "Objective: complete the tower, connect it to the road network and destroy every attacking unit.",
            "Start the attack",
            TutorialTriggerType::None,
            false
        },
        {
            TutorialTriggerType::DefenseRepelled,
            "From defence to counterattack",
            "The attack has been repelled. It is time to build the tools for an offensive. A Smith can turn {resource}Iron{/resource} and {resource}Wood{/resource} into {resource}Iron Swords{/resource}; "
            "other equipment chains can be added later as your army grows. Build a Smith and a Barracks, then recruit ten Light Infantry. "
            "Light Infantry mainly needs manpower and {resource}Food Provisions{/resource}, so keep your food and logistics running. "
            "Open the Roster, select the ten soldiers, choose the enemy Headquarters and deploy them along the military road. "
            "Objective: establish sword production, finish a Barracks, recruit 10 Light Infantry and deploy the group to attack.",
            "Start the counterattack",
            TutorialTriggerType::None,
            true
        }
    }};

    const TutorialPopupDefinition* FindPopupDefinition(TutorialTriggerType trigger)
    {
        for (const auto& definition : PopupDefinitions)
            if (definition.trigger == trigger)
                return &definition;
        return nullptr;
    }
}

TutorialScene::TutorialScene()
{
    // Keep the tutorial's debug shortcuts available for rapid testing. The
    // modal popup still pauses the world and blocks gameplay input until it is
    // dismissed, just like the regular tutorial flow.
    inputs.SetDebugActionsEnabled(true);
    tutorialPopup.UpdateSize({GetScreenWidth(), GetScreenHeight()});
    tutorialPopup.SetHorizontalOffset(-70);
    tutorialPopup.SetModalStateCallback([this](bool paused)
    {
        InputManager::SetInputEnabled(!paused);
        if (runtimeLoop != nullptr)
            runtimeLoop->SetPaused(paused);
    });
}

void TutorialScene::OnActivated()
{
    GameScene::OnActivated();
    InputManager::SetInputEnabled(!tutorialPopup.IsVisible());
}

void TutorialScene::HandleRenderDebugInput()
{
    GameScene::HandleRenderDebugInput();
    if (!InputManager::IsKeyPressed(KEY_F11) || tutorialPopup.IsVisible())
        return;

    // F11 is deliberately a tutorial-only accelerator. It advances the
    // current scripted milestone while leaving ordinary GameScene debug
    // shortcuts unchanged.
    if (activePopupTrigger == TutorialTriggerType::PracticeIntro || awaitingWoodcutter)
    {
            woodcutterCompletionReported = true;
            awaitingWoodcutter = false;
            EmitTrigger(TutorialTriggerType::BuildComplete, BuildingType::Woodcutter);
    }
    else if (activePopupTrigger == TutorialTriggerType::BuildComplete || awaitingRoadConnection)
    {
            roadConnectionReported = true;
            awaitingRoadConnection = false;
            EmitTrigger(TutorialTriggerType::LogisticsConnected);
    }
    else if (activePopupTrigger == TutorialTriggerType::BasicResourcesIntro || awaitingBasicProduction)
    {
            basicProductionReported = true;
            awaitingBasicProduction = false;
            EmitTrigger(TutorialTriggerType::BasicProductionComplete);
    }
    else if (activePopupTrigger == TutorialTriggerType::BasicProductionComplete ||
             (basicProductionReported && !foodChainReported))
    {
            foodChainReported = true;
            UnlockTutorialDecisions();
            EmitTrigger(TutorialTriggerType::FoodChainComplete);
    }
    else if (activePopupTrigger == TutorialTriggerType::FoodChainComplete ||
             (foodChainReported && !decisionSelectedReported))
    {
            decisionSelectedReported = true;
            EmitTrigger(TutorialTriggerType::DecisionSelected);
    }
    else if (activePopupTrigger == TutorialTriggerType::DecisionSelected || awaitingDefense)
    {
            awaitingDefense = true;
            StartScriptedDefenseAttack();
    }
    else if (activePopupTrigger == TutorialTriggerType::DefenseRepelled || counterattackStageActive)
    {
            counterattackStageActive = true;
    }

    if (awaitingDefense && defenseAttackStarted && !defenseReported)
    {
        if (auto* mutex = runtimeLoop != nullptr ? runtimeLoop->GetWorldMutex() : nullptr)
        {
            std::lock_guard<std::recursive_mutex> lock(*mutex);
            for (int id : scriptedEnemyUnitIds)
            {
                game->GetDeployedUnits().erase(id);
                for (const auto& [playerId, player] : game->GetPlayerHandler().players)
                    if (player != nullptr)
                        player->roster.units.erase(id);
            }
        }
        defenseReported = true;
        awaitingDefense = false;
        defenseRouteRevealActive = false;
        EmitTrigger(TutorialTriggerType::DefenseRepelled);
    }
}

void TutorialScene::PrepareGameplayRender()
{
    if (!defenseRouteRevealActive || game == nullptr || scriptedEnemyPlayerId < 0)
        return;

    const int localPlayerId = game->GetLocalPlayerId();
    const std::vector<int> route = game->GetMilitaryRoads().GetDirectedTiles(
        scriptedEnemyPlayerId, localPlayerId);
    for (int tileId : route)
    {
        const Vec2i tile = game->GetTileMap().GetCoordsFromId(tileId);
        const Vector2 center{
            static_cast<float>(tile.x * TILE_SIZE + TILE_SIZE / 2),
            static_cast<float>(tile.y * TILE_SIZE + TILE_SIZE / 2)};
        render.QueueFogReveal({center, FogOfWar::UnitRevealRadiusWorld * 1.35f});
    }
}

void TutorialScene::Update(double dt)
{
    GameScene::Update(dt);
    UpdateTutorialTasks();

    if (game == nullptr || runtimeLoop == nullptr || tutorialPopup.IsVisible())
        return;

    bool completed = false;
    bool connected = false;
    bool basicProductionReady = false;
    bool foodChainReady = false;
    bool decisionSelected = false;
    if (auto* mutex = runtimeLoop->GetWorldMutex())
    {
        std::lock_guard<std::recursive_mutex> lock(*mutex);
        auto playerIt = game->GetPlayerHandler().players.find(game->GetLocalPlayerId());
        if (playerIt != game->GetPlayerHandler().players.end() && playerIt->second != nullptr)
        {
            Player* player = playerIt->second.get();
            completed = awaitingWoodcutter && !woodcutterCompletionReported &&
                        player->HasTrackedBuilding(BuildingType::Woodcutter, true);
            if (awaitingRoadConnection && !roadConnectionReported)
            {
                Building* woodcutter = nullptr;
                Building* headquarters = nullptr;
                for (Building* building : player->GetTrackedBuildings())
                {
                    if (building == nullptr || building->IsUnderConstruction())
                        continue;
                    if (building->buildingType == BuildingType::Woodcutter && woodcutter == nullptr)
                        woodcutter = building;
                    if (building->buildingType == BuildingType::Headquarters && headquarters == nullptr)
                        headquarters = building;
                }
                if (woodcutter != nullptr && headquarters != nullptr && player->GetRoadNetwork() != nullptr)
                    connected = !player->GetRoadNetwork()->CalculatePath(woodcutter, headquarters).empty();
            }
            if (awaitingBasicProduction && !basicProductionReported)
            {
                basicProductionReady =
                    player->GetTrackedBuildingCount(BuildingType::Woodcutter, true) >= 2 &&
                    player->HasTrackedBuilding(BuildingType::LumberMill, true) &&
                    player->HasTrackedBuilding(BuildingType::Mine, true) &&
                    player->HasTrackedBuilding(BuildingType::Foundry, true);
            }

            if (basicProductionReported && !foodChainReported)
            {
                for (Building* building : player->GetTrackedBuildings())
                {
                    if (building != nullptr && building->buildingType == BuildingType::Inn &&
                        !building->IsUnderConstruction() && building->GetTotalProduced() > 0)
                    {
                        foodChainReady = true;
                        break;
                    }
                }
            }

            decisionSelected = !player->focuses.GetActiveFocusId().empty() ||
                               !player->focuses.GetUnlocked().empty();
        }
    }

    if (completed)
    {
        woodcutterCompletionReported = true;
        awaitingWoodcutter = false;
        EmitTrigger(TutorialTriggerType::BuildComplete, BuildingType::Woodcutter);
        return;
    }

    if (connected)
    {
        roadConnectionReported = true;
        awaitingRoadConnection = false;
        EmitTrigger(TutorialTriggerType::LogisticsConnected);
        return;
    }

    if (basicProductionReady)
    {
        basicProductionReported = true;
        awaitingBasicProduction = false;
        EmitTrigger(TutorialTriggerType::BasicProductionComplete);
        return;
    }

    if (foodChainReady)
    {
        foodChainReported = true;
        UnlockTutorialDecisions();
        EmitTrigger(TutorialTriggerType::FoodChainComplete);
        return;
    }

    if (counterattackStageActive && !counterattackDeployed)
        counterattackDeployed = IsCounterattackDeployed();

    if (foodChainReported && !decisionSelectedReported && decisionSelected)
    {
        decisionSelectedReported = true;
        EmitTrigger(TutorialTriggerType::DecisionSelected);
        return;
    }

    if (awaitingDefense && defenseAttackStarted && !defenseReported &&
        IsScriptedDefenseAttackCleared())
    {
        defenseReported = true;
        awaitingDefense = false;
        defenseRouteRevealActive = false;
        EmitTrigger(TutorialTriggerType::DefenseRepelled);
    }
}

void TutorialScene::UpdateTutorialTasks()
{
    if (game == nullptr)
        return;

    if (!taskCameraBaselineSet)
    {
        taskCameraStart = {render.camera.target.x, render.camera.target.y};
        taskCameraBaselineSet = true;
    }

    const float cameraDistance = std::abs(render.camera.target.x - taskCameraStart.x) +
                                 std::abs(render.camera.target.y - taskCameraStart.y);
    const bool cameraMoved = cameraDistance > 2.0f;
    if (controller != nullptr && controller->activeSystem != nullptr)
    {
        auto buildIt = controller->systems.find("build");
        if (buildIt != controller->systems.end() && controller->activeSystem == buildIt->second)
            taskBuildModeSeen = true;
    }

    int woodcutters = 0;
    bool lumberMill = false;
    bool mine = false;
    bool foundry = false;
    bool well = false;
    bool wheatFarm = false;
    bool windmill = false;
    bool bakery = false;
    bool huntersHut = false;
    bool inn = false;
    bool foodProvisionsProduced = false;
    bool guardTower = false;
    bool guardTowerConnected = false;
    int lightInfantryInRoster = 0;
    bool smith = false;
    bool barracks = false;
    if (runtimeLoop != nullptr)
    {
        if (auto* mutex = runtimeLoop->GetWorldMutex())
        {
            std::lock_guard<std::recursive_mutex> lock(*mutex);
            auto playerIt = game->GetPlayerHandler().players.find(game->GetLocalPlayerId());
            if (playerIt != game->GetPlayerHandler().players.end() && playerIt->second != nullptr)
            {
                Player* player = playerIt->second.get();
                woodcutters = player->GetTrackedBuildingCount(BuildingType::Woodcutter, true);
                lumberMill = player->HasTrackedBuilding(BuildingType::LumberMill, true);
                mine = player->HasTrackedBuilding(BuildingType::Mine, true);
                foundry = player->HasTrackedBuilding(BuildingType::Foundry, true);
                well = player->HasTrackedBuilding(BuildingType::Well, true);
                wheatFarm = player->HasTrackedBuilding(BuildingType::WheatFarm, true);
                windmill = player->HasTrackedBuilding(BuildingType::Windmill, true);
                bakery = player->HasTrackedBuilding(BuildingType::Bakery, true);
                huntersHut = player->HasTrackedBuilding(BuildingType::HuntersHut, true);
                inn = player->HasTrackedBuilding(BuildingType::Inn, true);
                for (Building* building : player->GetTrackedBuildings())
                {
                    if (building != nullptr && building->buildingType == BuildingType::Inn &&
                        !building->IsUnderConstruction() && building->GetTotalProduced() > 0)
                    {
                        foodProvisionsProduced = true;
                        break;
                    }
                }

                guardTower = player->HasTrackedBuilding(BuildingType::DefenseTower, true);
                smith = player->HasTrackedBuilding(BuildingType::Smith, true);
                barracks = player->HasTrackedBuilding(BuildingType::Barracks, true);
                Building* tower = nullptr;
                Building* headquarters = nullptr;
                for (Building* building : player->GetTrackedBuildings())
                {
                    if (building == nullptr || building->IsUnderConstruction())
                        continue;
                    if (building->buildingType == BuildingType::DefenseTower && tower == nullptr)
                        tower = building;
                    if (building->buildingType == BuildingType::Headquarters && headquarters == nullptr)
                        headquarters = building;
                }
                if (tower != nullptr && headquarters != nullptr && player->GetRoadNetwork() != nullptr)
                    guardTowerConnected = !player->GetRoadNetwork()->CalculatePath(tower, headquarters).empty();

                for (const auto& [instanceId, unit] : player->roster.units)
                    if (unit.unitDefId == "militia")
                        lightInfantryInRoster++;
            }
        }
    }

    if (activePopupTrigger == TutorialTriggerType::PracticeIntro || awaitingWoodcutter)
    {
        tutorialTasks.SetTasks("First production", {
            {"Pan the camera", cameraMoved},
            {"Open the Build panel (Q)", taskBuildModeSeen},
            {"Build a Woodcutter in a forest", woodcutterCompletionReported}
        });
    }
    else if (activePopupTrigger == TutorialTriggerType::BuildComplete || awaitingRoadConnection)
    {
        tutorialTasks.SetTasks("First logistics link", {
            {"Finish the Woodcutter", woodcutterCompletionReported},
            {"Connect Woodcutter to Headquarters", roadConnectionReported}
        });
    }
    else if (activePopupTrigger == TutorialTriggerType::LogisticsConnected)
    {
        tutorialTasks.SetTasks("People and productivity", {
            {"Review manpower and food indicators", false},
            {"Continue to the materials objective", false}
        });
    }
    else if (activePopupTrigger == TutorialTriggerType::BasicResourcesIntro || awaitingBasicProduction)
    {
        tutorialTasks.SetTasks("Basic materials", {
            {"Build a second Woodcutter", woodcutters >= 2},
            {"Build a Lumber Mill", lumberMill},
            {"Build a Mine", mine},
            {"Build a Foundry", foundry}
        });
    }
    else if (activePopupTrigger == TutorialTriggerType::FoodChainComplete ||
             (foodChainReported && !decisionSelectedReported))
    {
        tutorialTasks.SetTasks("Decisions", {
            {"Complete the Food Provisions chain", foodChainReported},
            {"Choose any first decision", decisionSelectedReported}
        });
    }
    else if (activePopupTrigger == TutorialTriggerType::DecisionSelected || awaitingDefense)
    {
        tutorialTasks.SetTasks("First defence", {
            {"Build a Defense Tower", guardTower},
            {"Connect the tower to Headquarters", guardTowerConnected},
            {"Repel the scripted attack", defenseReported}
        });
    }
    else if (activePopupTrigger == TutorialTriggerType::DefenseRepelled || counterattackStageActive)
    {
        tutorialTasks.SetTasks("Counterattack", {
            {"Build a Smith for Iron Swords", smith},
            {"Build a Barracks", barracks},
            {"Recruit 10 Light Infantry", lightInfantryInRoster >= 10},
            {"Deploy the group against the enemy Headquarters", counterattackDeployed}
        });
    }
    else if (activePopupTrigger == TutorialTriggerType::BasicProductionComplete || basicProductionReported)
    {
        tutorialTasks.SetTasks("Food chain", {
            {"Build a Well for Water", well},
            {"Build a Wheat Farm", wheatFarm},
            {"Build a Windmill", windmill},
            {"Build a Bakery", bakery},
            {"Build a Hunter's Hut for Meat", huntersHut},
            {"Build an Inn for Food Provisions", inn},
            {"Connect the chain and feed villages and towers", foodProvisionsProduced}
        });
    }
    else
    {
        tutorialTasks.SetTasks("Welcome", {{"Continue to the practice stage", false}});
    }
}

void TutorialScene::HandleEvent(std::shared_ptr<Event> e)
{
    if (auto resize = std::dynamic_pointer_cast<WindowSizeChangedEvent>(e))
    {
        GameScene::HandleEvent(e);
        tutorialPopup.UpdateSize(resize->windowSize);
        return;
    }

    if (auto sceneChange = std::dynamic_pointer_cast<ChangeSceneEvent>(e))
    {
        if (sceneChange->sceneName == "MainScene")
        {
            // Close the modal before tearing down the session so its generic
            // callback cannot leave a future tutorial world paused/unpaused
            // based on stale popup state.
            tutorialPopup.Hide();
            activePopupTrigger = TutorialTriggerType::None;
            awaitingWoodcutter = false;
            woodcutterCompletionReported = false;
            awaitingRoadConnection = false;
            roadConnectionReported = false;
            awaitingBasicProduction = false;
            basicProductionReported = false;
            foodChainReported = false;
            decisionSelectedReported = false;
            awaitingDefense = false;
            defenseAttackStarted = false;
            defenseReported = false;
            counterattackStageActive = false;
            counterattackDeployed = false;
            tutorialDecisionsUnlocked = false;
            scriptedEnemyPlayerId = -1;
            scriptedEnemyUnitIds.clear();
            defenseRouteRevealActive = false;
            taskCameraBaselineSet = false;
            taskBuildModeSeen = false;
            tutorialTasks.tasks.clear();
            ClearTutorialHighlights();
            SetTutorialHudLock(false);
            ShutdownActiveGame();
        }
        return;
    }

    if (auto tutorial = std::dynamic_pointer_cast<TutorialGameEvent>(e))
    {
        StartNewGame(tutorial->name, tutorial->params);
        activePopupTrigger = TutorialTriggerType::None;
        awaitingWoodcutter = false;
        woodcutterCompletionReported = false;
        awaitingRoadConnection = false;
        roadConnectionReported = false;
        awaitingBasicProduction = false;
        basicProductionReported = false;
        foodChainReported = false;
        decisionSelectedReported = false;
        awaitingDefense = false;
        defenseAttackStarted = false;
        defenseReported = false;
        counterattackStageActive = false;
        counterattackDeployed = false;
        tutorialDecisionsUnlocked = false;
        scriptedEnemyPlayerId = -1;
        scriptedEnemyUnitIds.clear();
        defenseRouteRevealActive = false;
        taskCameraBaselineSet = false;
        taskBuildModeSeen = false;
        tutorialTasks.tasks.clear();
        ClearTutorialHighlights();
        SetTutorialHudLock(true);
        ShowPopupForTrigger(TutorialTriggerType::None);

        auto changeScene = std::make_shared<ChangeSceneEvent>();
        changeScene->sender = this;
        changeScene->sceneName = "TutorialScene";
        changeScene->previousSceneName = name;
        broker->Broadcast(changeScene);
        return;
    }

    auto trigger = std::dynamic_pointer_cast<TutorialTriggerEvent>(e);
    if (trigger == nullptr)
        return;

    if (trigger->type == TutorialTriggerType::BuildComplete &&
        trigger->buildingType != BuildingType::Woodcutter)
        return;

    ShowPopupForTrigger(trigger->type, trigger->buildingType);
}

void TutorialScene::ShowPopupForTrigger(TutorialTriggerType trigger, BuildingType buildingType)
{
    const TutorialPopupDefinition* definition = FindPopupDefinition(trigger);
    if (definition == nullptr || tutorialPopup.IsVisible())
        return;

    if (trigger == TutorialTriggerType::BuildComplete && buildingType != BuildingType::Woodcutter)
        return;

    activePopupTrigger = trigger;
    tutorialPopup.SetDimBackground(definition->dimBackground);
    if (trigger == TutorialTriggerType::LogisticsConnected)
        OpenWoodcutterPanelAndHighlights();
    tutorialPopup.Show(definition->title, definition->body, definition->action,
                       [this]() { OnPopupDismissed(); });
}

void TutorialScene::OnPopupDismissed()
{
    const TutorialPopupDefinition* definition = FindPopupDefinition(activePopupTrigger);
    const TutorialTriggerType nextTrigger = definition != nullptr
        ? definition->nextTrigger
        : TutorialTriggerType::None;

    if (activePopupTrigger == TutorialTriggerType::PracticeIntro)
        awaitingWoodcutter = true;
    if (activePopupTrigger == TutorialTriggerType::BuildComplete)
        awaitingRoadConnection = true;
    if (activePopupTrigger == TutorialTriggerType::BasicResourcesIntro)
        awaitingBasicProduction = true;
    if (activePopupTrigger == TutorialTriggerType::BasicResourcesIntro)
        ClearTutorialHighlights();
    if (activePopupTrigger == TutorialTriggerType::DecisionSelected)
    {
        awaitingDefense = true;
        StartScriptedDefenseAttack();
    }
    if (activePopupTrigger == TutorialTriggerType::DefenseRepelled)
        counterattackStageActive = true;

    activePopupTrigger = TutorialTriggerType::None;
    tutorialPopup.Hide();

    if (nextTrigger != TutorialTriggerType::None)
        EmitTrigger(nextTrigger);
}

void TutorialScene::OpenWoodcutterPanelAndHighlights()
{
    if (controller == nullptr || game == nullptr || runtimeLoop == nullptr)
        return;

    auto systemIt = controller->systems.find("default");
    if (systemIt == controller->systems.end())
        return;
    auto* basic = dynamic_cast<BasicMapViewSystem*>(systemIt->second.get());
    if (basic == nullptr)
        return;

    auto* worldMutex = runtimeLoop->GetWorldMutex();
    if (worldMutex == nullptr)
        return;
    std::lock_guard<std::recursive_mutex> lock(*worldMutex);
    auto playerIt = game->GetPlayerHandler().players.find(game->GetLocalPlayerId());
    if (playerIt == game->GetPlayerHandler().players.end() || playerIt->second == nullptr)
        return;
    Building* woodcutter = nullptr;
    for (Building* building : playerIt->second->GetTrackedBuildings())
    {
        if (building != nullptr && building->buildingType == BuildingType::Woodcutter &&
            !building->IsUnderConstruction())
        {
            woodcutter = building;
            break;
        }
    }
    if (woodcutter == nullptr)
        return;

    controller->ChangeSystem("default");
    basic->SelectBuilding(woodcutter);
    basic->buildingInfoPanel.SetTutorialHighlight(true);
    basic->strategicHudWidget.SetTutorialHighlights(true, true);
}

void TutorialScene::ClearTutorialHighlights()
{
    if (controller == nullptr)
        return;
    auto systemIt = controller->systems.find("default");
    if (systemIt == controller->systems.end())
        return;
    auto* basic = dynamic_cast<BasicMapViewSystem*>(systemIt->second.get());
    if (basic == nullptr)
        return;
    basic->buildingInfoPanel.SetTutorialHighlight(false);
    basic->strategicHudWidget.SetTutorialHighlights(false, false);
}

void TutorialScene::SetTutorialHudLock(bool locked)
{
    tutorialHudLocked = locked;
    if (controller == nullptr)
        return;
    auto systemIt = controller->systems.find("default");
    if (systemIt == controller->systems.end())
        return;
    auto* basic = dynamic_cast<BasicMapViewSystem*>(systemIt->second.get());
    if (basic != nullptr)
        basic->strategicHudWidget.SetTutorialLockedButtons(locked);
}

void TutorialScene::UnlockTutorialDecisions()
{
    tutorialDecisionsUnlocked = true;
    tutorialHudLocked = false;
    if (controller == nullptr)
        return;

    auto systemIt = controller->systems.find("default");
    if (systemIt == controller->systems.end())
        return;
    auto* basic = dynamic_cast<BasicMapViewSystem*>(systemIt->second.get());
    if (basic == nullptr)
        return;

    // Keep Destroy and Resources disabled until the tutorial reaches a later
    // stage, but make Decisions the first tutorial-gated button to unlock.
    basic->strategicHudWidget.SetTutorialLockedButtons(true);
    basic->strategicHudWidget.SetTutorialDecisionsLocked(false);
}

void TutorialScene::StartScriptedDefenseAttack()
{
    if (defenseAttackStarted || game == nullptr || runtimeLoop == nullptr)
        return;

    auto* mutex = runtimeLoop->GetWorldMutex();
    if (mutex == nullptr)
        return;
    std::lock_guard<std::recursive_mutex> lock(*mutex);

    const int localPlayerId = game->GetLocalPlayerId();
    Player* enemy = nullptr;
    // Prefer a direct military-road neighbour so DeployUnits uses the same
    // route the player is seeing; fall back to the first live opponent.
    for (int neighbour : game->GetMilitaryRoads().GetNeighbors(localPlayerId))
    {
        auto it = game->GetPlayerHandler().players.find(neighbour);
        if (it != game->GetPlayerHandler().players.end() && it->second != nullptr &&
            !it->second->defeated)
        {
            enemy = it->second.get();
            break;
        }
    }
    if (enemy == nullptr)
    {
        for (const auto& [playerId, player] : game->GetPlayerHandler().players)
        {
            if (playerId != localPlayerId && player != nullptr && !player->defeated)
            {
                enemy = player.get();
                break;
            }
        }
    }
    if (enemy == nullptr)
        return;

    scriptedEnemyPlayerId = enemy->id;
    scriptedEnemyUnitIds.clear();
    constexpr int ScriptedAttackSize = 4;
    for (int i = 0; i < ScriptedAttackSize; ++i)
    {
        const int instanceId = enemy->id * 100000 + enemy->nextUnitInstanceId++;
        BattleUnit unit(instanceId, enemy->id, "militia");
        unit.currentHp = unit.GetEffectiveMaxHp(*enemy);
        enemy->roster.AddUnit(std::move(unit));
        scriptedEnemyUnitIds.push_back(instanceId);
    }

    // The first defence has an intentional tutorial reserve in the HQ, so the
    // player can focus on tower placement and logistics rather than waiting
    // for a complete ammunition economy before the exercise starts.
    Player* local = nullptr;
    auto localIt = game->GetPlayerHandler().players.find(localPlayerId);
    if (localIt != game->GetPlayerHandler().players.end())
        local = localIt->second.get();
    if (local != nullptr)
    {
        for (Building* building : local->GetTrackedBuildings())
        {
            if (building == nullptr || building->buildingType != BuildingType::Headquarters)
                continue;
            auto* storage = building->GetComponent<StorageComponent>();
            if (storage != nullptr)
            {
                auto& arrows = storage->buffers[ResourceType::ARROWS];
                if (arrows.type == ResourceType::Null)
                    arrows = ResourceBuffer{ResourceType::ARROWS, 120};
                arrows.bufferSize = std::max(arrows.bufferSize, 12);
                arrows.SetStoredAmount(std::max(12, static_cast<int>(arrows.buffer.size())));
            }
            break;
        }
    }

    // This is a local tutorial-only injection, not a player command. Move the
    // generated roster entries into the same deployed/spawn-queue structures
    // used by ExecuteCommand(DeployUnits), so the normal military march and
    // combat systems take over on the next simulation tick.
    const auto routeKey = std::make_pair(enemy->id, localPlayerId);
    for (int instanceId : scriptedEnemyUnitIds)
    {
        auto unit = enemy->roster.RemoveUnit(instanceId);
        if (!unit.has_value())
            continue;
        unit->state = BattleUnitState::Marching;
        unit->routeFromPlayerId = enemy->id;
        unit->routeToPlayerId = localPlayerId;
        unit->tileIndex = -1;
        unit->tileProgress = 0.0;
        unit->attackTimer = 0.0;
        game->GetDeployedUnits()[instanceId] = std::move(unit.value());
        game->GetSpawnQueues()[routeKey].push_back(instanceId);
    }
    defenseAttackStarted = true;
    defenseRouteRevealActive = true;

    for (Building* building : enemy->GetTrackedBuildings())
    {
        if (building == nullptr || building->buildingType != BuildingType::Headquarters)
            continue;
        const Vec2i anchor = game->GetTileMap().GetCoordsFromId(building->positionId);
        const Vec2f center{
            static_cast<float>(anchor.x * TILE_SIZE) + building->GetFootprint().x * TILE_SIZE * 0.5f,
            static_cast<float>(anchor.y * TILE_SIZE) + building->GetFootprint().y * TILE_SIZE * 0.5f};
        render.CenterCameraOnWorld(center, {game->GetTileMap().params.sizeX,
                                             game->GetTileMap().params.sizeY});
        break;
    }
}

bool TutorialScene::IsScriptedDefenseAttackCleared() const
{
    if (game == nullptr || runtimeLoop == nullptr || scriptedEnemyUnitIds.empty())
        return false;

    auto* mutex = runtimeLoop->GetWorldMutex();
    if (mutex == nullptr)
        return false;
    std::lock_guard<std::recursive_mutex> lock(*mutex);
    for (int id : scriptedEnemyUnitIds)
    {
        if (game->GetDeployedUnits().contains(id))
            return false;
        for (const auto& [playerId, player] : game->GetPlayerHandler().players)
        {
            if (player != nullptr && player->roster.FindUnit(id) != nullptr)
                return false;
        }
    }
    return true;
}

bool TutorialScene::IsCounterattackDeployed() const
{
    if (game == nullptr || runtimeLoop == nullptr || scriptedEnemyPlayerId < 0)
        return false;

    auto* mutex = runtimeLoop->GetWorldMutex();
    if (mutex == nullptr)
        return false;
    std::lock_guard<std::recursive_mutex> lock(*mutex);
    const int localPlayerId = game->GetLocalPlayerId();
    for (const auto& [instanceId, unit] : game->GetDeployedUnits())
    {
        if (unit.ownerPlayerId == localPlayerId && unit.routeToPlayerId == scriptedEnemyPlayerId &&
            unit.unitDefId == "militia" && unit.state != BattleUnitState::Dying)
            return true;
    }
    return false;
}

void TutorialScene::EmitTrigger(TutorialTriggerType trigger, BuildingType buildingType)
{
    auto event = std::make_shared<TutorialTriggerEvent>();
    event->sender = this;
    event->type = trigger;
    event->buildingType = buildingType;
    broker->Broadcast(event);
}
